fix(local-backup-s3): Create suspended CronJob for recovery job creation

diff --git a/k8s/apps/storage/local-backup-s3/crossplane-backup-buckets.k8s.yaml b/k8s/apps/storage/local-backup-s3/crossplane-backup-buckets.k8s.yaml
--- a/k8s/apps/storage/local-backup-s3/crossplane-backup-buckets.k8s.yaml
+++ b/k8s/apps/storage/local-backup-s3/crossplane-backup-buckets.k8s.yaml
@@ -279,3 +279,78 @@ spec:
               - fromFieldPath: spec.mirrorSchedule
                 toFieldPath: spec.forProvider.manifest.spec.schedule
                 type: FromCompositeFieldPath
+          - name: b2-recovery-cronjob
+            base:
+              apiVersion: kubernetes.crossplane.io/v1alpha2
+              kind: Object
+              spec:
+                forProvider:
+                  manifest:
+                    apiVersion: batch/v1
+                    kind: CronJob
+                    metadata:
+                      name: b2-to-local-recovery
+                    spec:
+                      concurrencyPolicy: Forbid
+                      suspend: true
+                      schedule: "0 0 31 2 *"
+                      successfulJobsHistoryLimit: 3
+                      failedJobsHistoryLimit: 3
+                      jobTemplate:
+                        spec:
+                          template:
+                            spec:
+                              restartPolicy: OnFailure
+                              containers:
+                                - name: mc-mirror
+                                  image: minio/mc:latest
+                                  command:
+                                    - /bin/sh
+                                    - -c
+                                    - |
+                                      set -e
+                                      mc alias set local https://backup-s3.${CLUSTER_DOMAIN} $LOCAL_ACCESS_KEY $LOCAL_SECRET_KEY
+                                      mc alias set remote https://s3.us-east-005.backblazeb2.com $REMOTE_ACCESS_KEY $REMOTE_SECRET_KEY
+
+                                      echo "WARNING: This job will overwrite local backups with remote ones, which are probably outdated."
+                                      echo "Make sure you know what you're doing. Sleeping for 2 minutes to give a chance to abort"
+                                      sleep 120
+                                      mc mirror --remove --overwrite remote/emnt-dev-$BUCKET_NAME local/$BUCKET_NAME
+                                  env:
+                                    - name: BUCKET_NAME
+                                      value: ""
+                                    - name: LOCAL_ACCESS_KEY
+                                      valueFrom:
+                                        secretKeyRef:
+                                          name: local-backup-s3-key
+                                          key: access_key
+                                    - name: LOCAL_SECRET_KEY
+                                      valueFrom:
+                                        secretKeyRef:
+                                          name: local-backup-s3-key
+                                          key: secret_key
+                                    - name: REMOTE_ACCESS_KEY
+                                      valueFrom:
+                                        secretKeyRef:
+                                          name: backblaze-b2-key
+                                          key: application_key_id
+                                    - name: REMOTE_SECRET_KEY
+                                      valueFrom:
+                                        secretKeyRef:
+                                          name: backblaze-b2-key
+                                          key: application_key
+            patches:
+              - fromFieldPath: metadata.labels["crossplane.io/claim-namespace"]
+                toFieldPath: metadata.name
+                type: FromCompositeFieldPath
+                transforms:
+                  - type: string
+                    string:
+                      type: Format
+                      fmt: "%s-backup-recovery-cronjob"
+              - fromFieldPath: metadata.labels["crossplane.io/claim-namespace"]
+                toFieldPath: spec.forProvider.manifest.metadata.namespace
+                type: FromCompositeFieldPath
+              - fromFieldPath: metadata.labels["crossplane.io/claim-namespace"]
+                toFieldPath: spec.forProvider.manifest.spec.jobTemplate.spec.template.spec.containers[0].env[0].value
+                type: FromCompositeFieldPath
