feat(nixos-deploy): Add SOPS step

diff --git a/k8s/apps/development/argo-workflows/workflow-templates/nixos-deploy.k8s.yaml b/k8s/apps/development/argo-workflows/workflow-templates/nixos-deploy.k8s.yaml
--- a/k8s/apps/development/argo-workflows/workflow-templates/nixos-deploy.k8s.yaml
+++ b/k8s/apps/development/argo-workflows/workflow-templates/nixos-deploy.k8s.yaml
@@ -16,6 +16,7 @@ metadata:
   namespace: argo-workflows
 spec:
   refreshInterval: "30m0s"
+  refreshPolicy: OnChange
   target:
     name: nixos-deploy-ssh-key
   dataFrom:
@@ -24,6 +25,19 @@ spec:
           apiVersion: generators.external-secrets.io/v1alpha1
           kind: SSHKey
           name: nixos-deploy-ssh-key
+---
+apiVersion: v1
+kind: Secret
+metadata:
+  name: placeholder-vm-secrets
+  namespace: argo-workflows
+stringData:
+  secrets.json: |
+    {
+      "test": {
+        "sops": "Testing sops encryption"
+      }
+    }
 ---
 # yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/clusterworkflowtemplate_v1alpha1.json
 apiVersion: argoproj.io/v1alpha1
@@ -49,6 +63,12 @@ spec:
         value: "https://github.com/eaglesemanation/ops.emnt.dev.git"
       - name: flakeAttr
         value: "placeholderVm"
+      - name: sopsSecretRef
+        description: Name of a k8s secret that contains "secrets.json". It will be converted into sops file for sops-nix use
+        value: "placeholder-vm-secrets"
+      - name: sopsSecretTargetPath
+        description: Path under flakeRepo where sops encrypted secrets should be written
+        value: nix/secrets.sops.json
 
   templates:
     - name: dag
@@ -56,6 +76,10 @@ spec:
         tasks:
           - name: ensure-known-hosts
             template: ensure-known-hosts
+          - name: encrypt-secrets
+            template: encrypt-secrets
+            dependencies:
+              - ensure-known-hosts
           - name: detect-mode
             template: detect-mode
             dependencies:
@@ -63,13 +87,23 @@ spec:
           - name: nixos-anywhere
             template: nixos-anywhere
             dependencies:
+              - encrypt-secrets
               - detect-mode
             when: '"{{tasks.detect-mode.outputs.parameters.mode}}" == "bootstrap"'
+            arguments:
+              artifacts:
+                - name: secretsSops
+                  from: "{{tasks.encrypt-secrets.outputs.artifacts.secretsSops}}"
           - name: deploy-rs
             template: deploy-rs
             dependencies:
+              - encrypt-secrets
               - detect-mode
             when: '"{{tasks.detect-mode.outputs.parameters.mode}}" == "deploy"'
+            arguments:
+              artifacts:
+                - name: secretsSops
+                  from: "{{tasks.encrypt-secrets.outputs.artifacts.secretsSops}}"
 
     - name: ensure-known-hosts
       script:
@@ -99,13 +133,57 @@ spec:
           if [ "$REPLACE_KEY" = "true" ]; then
             ssh-keygen -R "$HOST" -f "$KNOWN_HOSTS" || true
           fi
-          if ! grep -v '^[[:space:]]*#' "$KNOWN_HOSTS" | grep -q "$HOST"; then
-            ssh-keyscan -H "$HOST" >> "$KNOWN_HOSTS"
+          if ! grep -q "$HOST" "$KNOWN_HOSTS"; then
+            ssh-keyscan "$HOST" | grep -v '^#' >> "$KNOWN_HOSTS"
           fi
 
           kubectl create secret generic "$SECRET_NAME" \
             --from-file=known_hosts="$KNOWN_HOSTS" \
             --dry-run=client -o yaml | kubectl apply -f -
+
+    - name: encrypt-secrets
+      outputs:
+        artifacts:
+          - name: secretsSops
+            path: /tmp/secrets.sops.json
+      script:
+        image: docker.io/library/alpine:3.23.3
+        securityContext:
+          runAsNonRoot: false
+          readOnlyRootFilesystem: false
+          runAsUser: 0
+        command: [sh]
+        source: |
+          set -eux
+          HOST="{{workflow.parameters.targetHost}}"
+
+          apk add go sops
+          go install github.com/Mic92/ssh-to-age/cmd/ssh-to-age@latest
+
+          SSH_PUBKEY="$(cat /root/.ssh/known_hosts | grep "$HOST" | grep 'ssh-ed25519')"
+          if [[ -z "$SSH_PUBKEY" ]]; then
+            echo "ERROR: No ssh-ed25519 entry found for host '$HOST' in known_hosts" >&2
+            exit 1
+          fi
+          AGE_PUBKEY="$(echo "$SSH_PUBKEY"| /root/go/bin/ssh-to-age)"
+
+          sops --encrypt --age "$AGE_PUBKEY" --output "/tmp/secrets.sops.json" /tmp/secrets.json
+        volumeMounts:
+          - name: known-hosts
+            mountPath: /root/.ssh/known_hosts
+            subPath: known_hosts
+          - name: secrets-source
+            mountPath: /tmp/secrets.json
+            subPath: secrets.json
+      volumes:
+        - name: known-hosts
+          secret:
+            secretName: "nixos-known-hosts"
+            defaultMode: 384 # 0600
+        - name: secrets-source
+          secret:
+            secretName: "{{workflow.parameters.sopsSecretRef}}"
+            defaultMode: 384 # 0600
 
     - name: detect-mode
       script:
@@ -169,11 +247,16 @@ spec:
             defaultMode: 384 # 0600
 
     - name: nixos-anywhere
+      inputs:
+        artifacts:
+          - name: secretsSops
+            path: /tmp/secrets.sops.json
       script:
         # image: docker.io/nixos/nix:2.34.6
         image: docker.io/library/alpine:3.23.3
         command: [sh]
         source: |
+          cat /tmp/secrets.sops.json
           echo 'nixos-anywhere would be executed'
         volumeMounts:
           - name: known-hosts
@@ -196,11 +279,16 @@ spec:
             defaultMode: 384 # 0600
 
     - name: deploy-rs
+      inputs:
+        artifacts:
+          - name: secretsSops
+            path: /tmp/secrets.sops.json
       script:
         # image: docker.io/nixos/nix:2.34.6
         image: docker.io/library/alpine:3.23.3
         command: [sh]
         source: |
+          cat /tmp/secrets.sops.json
           echo 'deploy-rs would be executed'
         volumeMounts:
           - name: known-hosts
